In [1]:
!python --version
#python = 3.10, tensorflow=2.10, cuda=

Python 3.10.16


In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np 
import pandas as pd


In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
import tensorflow as tf


In [5]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
tf.test.is_built_with_cuda()

True

In [7]:
fashion_mnist = keras.datasets.fashion_mnist

In [8]:
fashion_mnist

<module 'keras.api._v2.keras.datasets.fashion_mnist' from 'C:\\Users\\sanjay\\anaconda3\\envs\\py310\\lib\\site-packages\\keras\\api\\_v2\\keras\\datasets\\fashion_mnist\\__init__.py'>

In [9]:
(train_image, train_labels),(test_image, test_labels) = fashion_mnist.load_data()

In [10]:
train_image.shape

(60000, 28, 28)

In [11]:
k = pd.DataFrame(data=train_labels)

In [12]:
k.value_counts()

0    6000
1    6000
2    6000
3    6000
4    6000
5    6000
6    6000
7    6000
8    6000
9    6000
dtype: int64

In [13]:
classes = ["T-shirt/top", "Trouser", "Pullover", "dress", "coat", "sandel", "shirt", "sneaker", "bag", "ankleboot"]

In [14]:
train_image = train_image/255
test_image = test_image/255

In [15]:
train_image[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [16]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [17]:
train_image.shape

(60000, 28, 28)

                                                    ONEHOTENCODING IN DEEP LEARNING

In [18]:
y_train = keras.utils.to_categorical(train_labels,num_classes=10, dtype= "float32")
y_test = keras.utils.to_categorical(test_labels,num_classes=10, dtype= "float32")

In [19]:
28*28

784

In [20]:
y_train[0:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [21]:
train_image[1]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00392157, 0.        , 0.        , 0.        , 0.        ,
        0.16078431, 0.7372549 , 0.40392157, 0.21176471, 0.18823529,
        0.16862745, 0.34117647, 0.65882353, 0.52156863, 0.0627451 ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00392157, 0.        ,
        0.        , 0.        , 0.19215686, 0.53333333, 0.85882353,
        0.84705882, 0.89411765, 0.9254902 , 1.        , 1.        ,
        1.        , 1.        , 0.85098039, 0.84313725, 0.99607843,
        0.90588235, 0.62745098, 0.17647059, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.05490196, 0.69019608, 0.87058824, 0.87843137, 0.83137255,
        0.79607843, 0.77647059, 0.76862745, 0.78431373, 0.84313725,
        0.8       , 0.7921

In [22]:


    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28,28)),
        keras.layers.Dense(600, activation="relu"),
        keras.layers.Dense(300, activation="relu"),
        keras.layers.Dense(10, activation="sigmoid")
    ])

    model.compile(optimizer="SGD",
                loss="categorical_crossentropy",
                metrics=["accuracy"]
                )
    model.fit(train_image, y_train, epochs=1)
    

1875/1875 [==============================] - 24s 11ms/step - loss: 0.6742 - accuracy: 0.7795


In [23]:
train_image.shape

(60000, 28, 28)

In [24]:
y_train.shape

(60000, 10)

In [25]:
classes[np.argmax(model.predict(test_image)[0])]

313/313 [==============================] - 1s 4ms/step


'ankleboot'

In [26]:
test_labels[0]

9

In [22]:
def getmodel():
    
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28,28)),
        keras.layers.Dense(700, activation="relu"),
        keras.layers.Dense(300, activation="relu"),
        keras.layers.Dense(10, activation="sigmoid")
    ])

    model.compile(optimizer="SGD",
                loss="categorical_crossentropy",
                metrics=["accuracy"]
                )
    return model

In [25]:
%%timeit -n1 -r1 
with tf.device("/CPU:0"):
    model = getmodel()
    model.fit(train_image, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.6673 - accuracy: 0.7824
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.4680 - accuracy: 0.8368
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.4259 - accuracy: 0.8500
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3980 - accuracy: 0.8597
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.3792 - accuracy: 0.8658
40.3 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [26]:
%%timeit -n1 -r1 
with tf.device('/GPU:0'):
     model = getmodel()
     model.fit(train_image, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.6648 - accuracy: 0.7842
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4691 - accuracy: 0.8350
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4245 - accuracy: 0.8518
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3998 - accuracy: 0.8601
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3778 - accuracy: 0.8671
17.4 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
