In [1]:
import numpy as np 

ypredicted = np.array([1,1,0,0,1])
ytruth = np.array([0.2, 0.3, 0.4, 0, 1])
                                                                                            


In [23]:
def mae(yt, yp):
    totalerror = 0  
    for t,p in zip(yt, yp):
        totalerror += abs(t - p)
    print("total error : ", totalerror)
    mae = totalerror/ len(yt)
    print("mae : ", mae )
    return mae
                                                                                        # without numpy
    

In [25]:
mae(ytruth, ypredicted)

total error :  1.9
mae :  0.38


0.38

In [29]:
                                                                                        # with numpy
k = np.mean(np.abs(ytruth - ypredicted))
print("mae:", k )

mae: 0.38


In [31]:
ypredicted

array([1, 1, 0, 0, 1])

In [55]:
eplison = 1e-15

yp = [min(1-eplison, i) for i in ypredicted]
yp = [max(eplison, i) for i in yp]
np.array(yp)

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [57]:
np.log(yp)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [63]:
-np.mean(ytruth* np.log(yp) + (1 -  ytruth) * np.log(1 - yp))

13.12497490929512

In [61]:
import numpy as np

# Ensure ytruth and yp are numpy arrays
ytruth = np.array(ytruth)
yp = np.array(yp)

# Now compute the log loss (binary cross-entropy)
loss = -np.mean(ytruth * np.log(yp) + (1 - ytruth) * np.log(1 - yp))

print(loss)

13.12497490929512
